// dataProduk.jsx
// import produk1 from '../photo/1.png'

const dataProduk = [
  {
    id: 1,
    nama: "Desire Driver",
    harga: "70 USD",
    kategori: "driver",
    foto: "produk1",
  },
  {
    id: 2,
    nama: "CSM Altering",
    harga: "300 USD",
    kategori: "figure",
    foto: "produk2.jpg",
  },
  {
    id: 3,
    nama: "Arcle (Legend Henshin Belt Series) ",
    harga: "35 USD",
    kategori: "driver",
    foto: "produk3.jpg",
  },
  {
    id: 4,
    nama: "CSM HENSHIN BELT TYPHOON ",
    harga: "500 USD",
    kategori: "driver",
    foto: "produk4.jpg",
  },
  {
    id: 5,
    nama: "Typhoon (Legend Henshin Belt Series) ",
    harga: "35 USD",
    kategori: "driver",
    foto: "produk5.jpg",
  },
  {
    id: 6,
    nama: "Decadriver & K-Touch (ver 2.0)",
    harga: "330 USD",
    kategori: "driver",
    foto: "produk6.jpg",
  },
  {
    id: 7,
    nama: "Faiz Smart Brain Kamen Rider",
    harga: "15 USD",
    kategori: "figure",
    foto: "produk7.jpg",
  },
  {
    id: 8,
    nama: "Kabuto Kamen Rider",
    harga: "15 USD",
    kategori: "figure",
    foto: "produk8.jpg",
  },
  {
    id: 9,
    nama: "Team Baron Lockseed Set",
    harga: "125 USD",
    kategori: "driver",
    foto: "produk9.jpg",
  },
  {
    id: 10,
    nama: "Rider Card Set (Extra) ",
    harga: "72 USD",
    kategori: "driver",
    foto: "produk10.jpg",
  },
  {
    id: 11,
    nama: "Kamen Rider Converge Motion ",
    harga: "56 USD",
    kategori: "figure",
    foto: "produk11.jpg",
  },
  {
    id: 12,
    nama: "GABUGABURIVOLVER & GABUGABURICALIBUR",
    harga: "175 USD",
    kategori: "driver",
    foto: "produk12.jpg",
  },
  {
    id: 13,
    nama: "SP LICENCE & SP LICENCE FS SET",
    harga: "219 USD",
    kategori: "driver",
    foto: "produk13.jpg",
  },
  {
    id: 14,
    nama: "SUPER SENTAI ARTISAN DRAGON BUCKLER",
    harga: "139 USD",
    kategori: "driver",
    foto: "produk14.jpg",
  },
  {
    id: 15,
    nama: "SUPER SENTAI ARTISAN DEGITAIZER & BATTLERAIZER",
    harga: "153 USD",
    kategori: "driver",
    foto: "produk15.jpg",
  },
  {
    id: 16,
    nama: "SUPER SENTAI ARTISAN KEITAIZER",
    harga: "104 USD",
    kategori: "driver",
    foto: "produk16.jpg",
  },
  {
    id: 17,
    nama: "DARK SEIZA BLASTER",
    harga: "74 USD",
    kategori: "driver",
    foto: "produk17.jpg",
  },
  {
    id: 18,
    nama: "GOSEIGATTAI DX DAIRENOH",
    harga: "294 USD",
    kategori: "figure",
    foto: "produk18.jpg",
  },
  {
    id: 19,
    nama: "BRAVE KYORYUZIN SET",
    harga: "241 USD",
    kategori: "figure",
    foto: "produk19.jpg",
  },
  {
    id: 20,
    nama: "TAMASHII Lab Dragon Symphony ZYUSOUKEN",
    harga: "180 USD",
    kategori: "driver",
    foto: "produk20.jpg",
  },
  {
    id: 21,
    nama: "High Proportion Collection ",
    harga: "27 USD",
    kategori: "driver",
    foto: "produk21.jpg",
  },
  {
    id: 22,
    nama: "TAIYO SENTAI SUN VULCAN",
    harga: "77 USD",
    kategori: "figure",
    foto: "produk22.jpg",
  },
];

export default dataProduk;
